"""Add cat_id to missions

Revision ID: 7355525a66eb
Revises: 
Create Date: 2024-12-23 00:36:48.883746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7355525a66eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missions')
    op.drop_index('ix_targets_id', table_name='targets')
    op.drop_table('targets')
    op.drop_index('ix_cats_id', table_name='cats')
    op.drop_table('cats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('years_of_experience', sa.INTEGER(), nullable=True),
    sa.Column('breed', sa.VARCHAR(), nullable=True),
    sa.Column('salary', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cats_id', 'cats', ['id'], unique=False)
    op.create_table('targets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mission_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('country', sa.VARCHAR(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('complete', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_targets_id', 'targets', ['id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
